# Generated by Django 5.0.14 on 2026-05-15 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregas/', verbose_name='archivo')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='fecha de entrega')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='nota')),
                ('observacion', models.TextField(blank=True, verbose_name='observación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('calificado', 'Calificado')], default='pendiente', max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'entrega de tarea',
                'verbose_name_plural': 'entregas de tareas',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='nota')),
                ('tipo', models.CharField(choices=[('examen', 'Examen'), ('tarea', 'Tarea'), ('participacion', 'Participación'), ('proyecto', 'Proyecto')], default='examen', max_length=20, verbose_name='tipo')),
                ('periodo', models.CharField(blank=True, max_length=50, verbose_name='periodo')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('observacion', models.TextField(blank=True, verbose_name='observación')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='fecha de publicación')),
                ('fecha_entrega', models.DateField(verbose_name='fecha de entrega')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tareas/', verbose_name='archivo adjunto')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
