# Generated by Django 5.0.14 on 2026-05-15 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academicos', '0001_initial'),
        ('gestion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='usuarios.alumno', verbose_name='alumno'),
        ),
        migrations.AddField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuarios.alumno', verbose_name='alumno'),
        ),
        migrations.AddField(
            model_name='nota',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion.asignatura', verbose_name='asignatura'),
        ),
        migrations.AddField(
            model_name='nota',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_cargadas', to='usuarios.profesor', verbose_name='profesor'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestion.asignatura', verbose_name='asignatura'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to='usuarios.profesor', verbose_name='profesor'),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academicos.tarea', verbose_name='tarea'),
        ),
        migrations.AlterUniqueTogether(
            name='entregatarea',
            unique_together={('tarea', 'alumno')},
        ),
    ]
