# Generated by Django 5.0.14 on 2026-05-15 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academicos", "0002_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarea",
            name="profesor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tareas_creadas",
                to="usuarios.profesor",
                verbose_name="profesor",
            ),
        ),
    ]
