# Generated by Django 5.0.14 on 2026-05-15 01:17

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academicos", "0003_alter_tarea_profesor"),
        ("gestion", "0002_initial"),
        ("usuarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAsistencia",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="fecha")),
                (
                    "presente",
                    models.BooleanField(default=True, verbose_name="presente"),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="observación"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.alumno",
                        verbose_name="alumno",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gestion.asignatura",
                        verbose_name="asignatura",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.profesor",
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical asistencia",
                "verbose_name_plural": "historical asistencias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEntregaTarea",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "archivo",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="archivo"
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="fecha de entrega"
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="nota",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="observación"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("entregado", "Entregado"),
                            ("calificado", "Calificado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.alumno",
                        verbose_name="alumno",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="academicos.tarea",
                        verbose_name="tarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical entrega de tarea",
                "verbose_name_plural": "historical entregas de tareas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalNota",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="nota",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("examen", "Examen"),
                            ("tarea", "Tarea"),
                            ("participacion", "Participación"),
                            ("proyecto", "Proyecto"),
                        ],
                        default="examen",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(blank=True, max_length=50, verbose_name="periodo"),
                ),
                (
                    "fecha",
                    models.DateField(blank=True, editable=False, verbose_name="fecha"),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="observación"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.alumno",
                        verbose_name="alumno",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gestion.asignatura",
                        verbose_name="asignatura",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.profesor",
                        verbose_name="profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical nota",
                "verbose_name_plural": "historical notas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTarea",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("descripcion", models.TextField(verbose_name="descripción")),
                (
                    "fecha_publicacion",
                    models.DateField(
                        blank=True, editable=False, verbose_name="fecha de publicación"
                    ),
                ),
                ("fecha_entrega", models.DateField(verbose_name="fecha de entrega")),
                (
                    "archivo",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="archivo adjunto",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gestion.asignatura",
                        verbose_name="asignatura",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.profesor",
                        verbose_name="profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tarea",
                "verbose_name_plural": "historical tareas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="fecha")),
                (
                    "presente",
                    models.BooleanField(default=True, verbose_name="presente"),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="observación"),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="usuarios.alumno",
                        verbose_name="alumno",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="gestion.asignatura",
                        verbose_name="asignatura",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asistencias_registradas",
                        to="usuarios.profesor",
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "asistencia",
                "verbose_name_plural": "asistencias",
                "ordering": ["-fecha"],
                "unique_together": {("alumno", "asignatura", "fecha")},
            },
        ),
    ]
