# Generated by Django 5.0.14 on 2026-05-15 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncurso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.profesor', verbose_name='profesor'),
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gestion.asignatura', verbose_name='asignatura'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'anio')},
        ),
        migrations.AddField(
            model_name='asignatura',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='gestion.curso', verbose_name='curso'),
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gestion.curso', verbose_name='curso'),
        ),
        migrations.AlterUniqueTogether(
            name='asignatura',
            unique_together={('nombre', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='asignacioncurso',
            unique_together={('profesor', 'curso', 'asignatura')},
        ),
    ]
