# Generated by Django 5.0.14 on 2026-05-15 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CicloLectivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="fecha de fin")),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
            ],
            options={
                "verbose_name": "ciclo lectivo",
                "verbose_name_plural": "ciclos lectivos",
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="ciclo_lectivo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos",
                to="gestion.ciclolectivo",
                verbose_name="ciclo lectivo",
            ),
        ),
    ]
