# Generated by Django 5.0.14 on 2026-05-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="horario_atencion",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="horario de atención"
            ),
        ),
        migrations.AddField(
            model_name="profesor",
            name="telefono",
            field=models.CharField(blank=True, max_length=50, verbose_name="teléfono"),
        ),
    ]
